// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkrumiddnoegilmwavkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rcnVtaWRkbm9lZ2lsbXdhdmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTYyNjYsImV4cCI6MjA2MjM3MjI2Nn0.X0iYxvTDr9LuErbA7ShuWa7qMejsinGWHQAHI90c_E4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);